//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hostel_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
      

        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string EmailAdress { get; set; }
        public string PhoneNo { get; set; }
        public string CNIC { get; set; }
        public string Adress { get; set; }
        public string Degree { get; set; }
        public string DepartmentName { get; set; }
        public string RegistrationNo { get; set; }
        public string HostelName { get; set; }
        public int RoomNo { get; set; }
    }
}
